coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error
        if_not_found: success
        if_no_uploads: error
    patch:
      default:
        target: 60%
        threshold: 10%
        if_ci_failed: error
        if_not_found: success
        if_no_uploads: error

  ignore:
    - 'tests/**/*'
    - 'src/tests/**/*'
    - '**/*.test.ts'
    - '**/*.spec.ts'
    - 'node_modules/**/*'
    - 'dist/**/*'
    - 'coverage/**/*'
    - 'scripts/**/*'
    - '.github/**/*'

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: no
